// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcUzsUgRTQQYYTu81W6MnCQmWXYxNdcC4',
    appId: '1:438813462334:web:6e0ba6c3bb17b7b184666f',
    messagingSenderId: '438813462334',
    projectId: 'projet-map-814a0',
    authDomain: 'projet-map-814a0.firebaseapp.com',
    storageBucket: 'projet-map-814a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8JxdEG1aY5HLcSjbIwgjUDhCKUCDIOA',
    appId: '1:438813462334:android:32a829a9df0c645084666f',
    messagingSenderId: '438813462334',
    projectId: 'projet-map-814a0',
    storageBucket: 'projet-map-814a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB686ZMXKwYGmVmZFIeNCOk5kalTYkQ07k',
    appId: '1:438813462334:ios:34de7ae10e2fc9fd84666f',
    messagingSenderId: '438813462334',
    projectId: 'projet-map-814a0',
    storageBucket: 'projet-map-814a0.appspot.com',
    iosClientId: '438813462334-qoem4vbuf91km0a5a2fokhbp56mo7kvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB686ZMXKwYGmVmZFIeNCOk5kalTYkQ07k',
    appId: '1:438813462334:ios:309f64aa48a2b10384666f',
    messagingSenderId: '438813462334',
    projectId: 'projet-map-814a0',
    storageBucket: 'projet-map-814a0.appspot.com',
    iosClientId: '438813462334-ra41364bn0j4dsetkc9annh909o535id.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapFlutter.RunnerTests',
  );
}
